app = "dataapi"          # ⚠️ 這裡要跟 Fly dashboard 上 App 名稱完全一致
primary_region = "sin"   # 東京，可改成你要的地區

[build]
dockerfile = "Dockerfile"

[processes]
worker = "python /app/dataAPI.py"

[[vm]]
  memory_mb = 1024
  cpus = 1
  cpu_kind = "shared"
  processes = ["worker"]

# [[mounts]]
#  source = "data"
#  destination = "/data"
